export const assests = {
  SOYUMMY_MAIN_LOGO: "/assests/images/soyummy-image.svg",
  MAIN_BACKGROUNG_IMAHE: "/assests/images/main-Background.svg",
  MAIN_BACKGROUNG_IMAHE_TWO: "/assests/images/background-2.svg",
  TIMER_ICON: "/assests/images/timer-icon.svg",
  STAR: "/assests/images/star.svg",
  LETS_START_WITH_EMOJI: "/assests/images/lets-start-with-emoji.svg",
  PERSON: "/assests/images/person.png",
  SOYUMMY_MAIN_LOGO_SMALL: "/assests/images/SYlogo-small.svg",
  ARROW_LEFT: "/assests/images/arrow-left.svg",
  OPTION_ONE: "/assests/images/option-1.svg",
  OPTION_TWO: "/assests/images/option-2.svg",
  OPTION_THREE: "/assests/images/option-3.svg",
  OPTION_FOUR: "/assests/images/option-4.svg",
};
